<a href="https://colab.research.google.com/github/SadeenAlsabbagh/Computer-Vision/blob/main/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#pytorch-fundementals

```
# resrouce: https://www.learnpytorch.io/00_pytorch_fundamentals/
```



In [ ]:
import torch
import pandas as pd
import numpy as no
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [ ]:
#to create tensors: in scaler
scalar= torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#to get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector= torch.tensor([7,7])
vector # we can check the number of dimensions for a vector by the number of square brackets

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix- building blocks: a 2dim arrays of numbers
matrix= torch.tensor([[7,1],
                     [3,2]]) # two square pairings
matrix

tensor([[7, 1],
        [3, 2]])

### Random tensors

why random tensors: the way many neiral networks learn, they start with with tensrs full of random numbers and then adjust those random numbers to better represent data.

In [ ]:
#create a random tensor of size (3,4)- three of 4 pairs
random_tensor= torch.rand(10,3,4)
random_tensor

tensor([[[0.2803, 0.7031, 0.2717, 0.9872],
         [0.9526, 0.2118, 0.9501, 0.0111],
         [0.3813, 0.7224, 0.4704, 0.3376]],

        [[0.6637, 0.4526, 0.3517, 0.1883],
         [0.5646, 0.6945, 0.5963, 0.5928],
         [0.7456, 0.0268, 0.5232, 0.3154]],

        [[0.1061, 0.8206, 0.8473, 0.0736],
         [0.1768, 0.5374, 0.6191, 0.0620],
         [0.6806, 0.2226, 0.4803, 0.5892]],

        [[0.8683, 0.3527, 0.7841, 0.9141],
         [0.6570, 0.0944, 0.5831, 0.0489],
         [0.0061, 0.3975, 0.3943, 0.0704]],

        [[0.4026, 0.5211, 0.7222, 0.8419],
         [0.3930, 0.1797, 0.4914, 0.4667],
         [0.1233, 0.4276, 0.0607, 0.6683]],

        [[0.7888, 0.1877, 0.8067, 0.1537],
         [0.5680, 0.7791, 0.9772, 0.7698],
         [0.4355, 0.6900, 0.6009, 0.7690]],

        [[0.5707, 0.8808, 0.3719, 0.3672],
         [0.8030, 0.5914, 0.1923, 0.4980],
         [0.5289, 0.1132, 0.2158, 0.1970]],

        [[0.5992, 0.4239, 0.8290, 0.1440],
         [0.1382, 0.5992, 0.1099, 0.2231

In [ ]:
# to encode an image of 224x224 into a tensor format
random_image_size_tensor=torch.rand(size=(3,224,224)) #height, width, color (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim #this is important bc, start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones Tensors

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros #to determine the data type: ones.dtype

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### creating a range of tensors and tensors-like

In [ ]:
#torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

#we can also define the step
one_to_ten = torch.arange(start=1, end = 11 , step= 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like & get depricated message
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
***Note***: Tensor datatypes are one of the three errors you might run into with PyTorch:
1. Tensors not right data types
2.  Tensors not right shape
3.  Tensors not right device

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, #what data type is the tensor
                               device = None, #by default is the tnesor is going to be a cpu/CUDA
                               requires_grad= False) # whether or not we need to track the gradiant for this tensor
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
#in order to change tensor datatypes - to test the data types for your tensors
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor #you can also have tensor operations between long, int, float

tensor([3., 6., 9.], dtype=torch.float16)

### Getting information from tensors
1. Tensors not right data types-- to get datatype from tensor, can use 'tensor.dtyp'
2. Tensors not right shape-- to get shape from tensor, can use 'tensor.shape'
3. Tensors not right device-- to get device from tensor, can use 'tensor.device'

In [ ]:
#an attribute is written without the bracket, a function is written with the brackets
vector= torch.rand([7,7])
vector.size()

torch.Size([7, 7])

In [ ]:
#find out details about teh tensor
print(vector)
print(f"Datatype of tensor: {vector.dtype}")
print(f"Shape of tensor: {vector.shape}")
print(f"Device tensor is stored on: {vector.device}")

tensor([[0.3198, 0.6514, 0.6628, 0.5746, 0.3641, 0.2038, 0.1551],
        [0.3907, 0.5906, 0.3651, 0.8303, 0.9522, 0.7480, 0.8260],
        [0.6939, 0.9112, 0.1699, 0.4553, 0.0908, 0.7043, 0.6033],
        [0.6733, 0.3518, 0.2221, 0.2043, 0.9938, 0.6823, 0.3727],
        [0.9118, 0.2535, 0.8562, 0.9775, 0.2611, 0.1181, 0.0557],
        [0.6047, 0.3961, 0.6991, 0.5191, 0.2734, 0.8943, 0.5881],
        [0.1926, 0.7060, 0.9028, 0.0696, 0.3623, 0.7412, 0.5985]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([7, 7])
Device tensor is stored on: cpu


### minpulating tensors (tensor operations)

* addition
* subtraction
* multiplication (element-wise): multiply each element by the number
* division
* matrix multiplication (dot product)

there are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimention** must match: ex. (2,3) @/matmul (3,2)
2. the resulting matrix has the shape of the **outer dimensions**: ex. (2,3) @/matmul (3,2) = (2,2)

In [ ]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# element wise multiplication
print (tensor, '*', tensor)
print(f'Element wise multiplication: {tensor * tensor}')
# element wise division
print(f'Element wise division: {tensor / tensor}')
# element wise subtraction
print(f'Element wise subtraction: {tensor - tensor}')
# element wise addition
print(f'Element wise addition: {tensor + tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Element wise multiplication: tensor([1, 4, 9])
Element wise division: tensor([1., 1., 1.])
Element wise subtraction: tensor([0, 0, 0])
Element wise addition: tensor([2, 4, 6])


In [ ]:
#matrix multiplication
torch.matmul(tensor, tensor)

#matric multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
#using a for loop to do the matrix multiplication by hand

%%time
value = 0
for i in range (len(tensor)):
  value += tensor [i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.4 ms, sys: 89 µs, total: 3.49 ms
Wall time: 4.41 ms


### Shape errors: most common errors

In [ ]:
#shapes for matrix multiplications
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

to fix the tensor shape errors/issues, we can minpulate the shape of one of our tensors using a transpose
a **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

##Tensor aggregation (min, max, mean, sum)

In [ ]:
x= torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() #we have to change the datatype of the tensor since it was initially a long

(tensor(46.), tensor(46.))

## finding the positional min and max

In [ ]:
x.argmin()  #positional min

tensor(0)

In [ ]:
#find the position/index in tensor that has the max
x.argmax()  #positional max

tensor(9)

In [ ]:
x[9]

tensor(91)

##reshaping, stacking, squeezing, and unsqueezing tensors (minpulate tensor shape issues)
* reshaping- reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the orignal tensor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - remove all '1' dimensions from a tensor
* unsqueeze - add a 1 dimention to a target tensor
* permute - return a view of the inpit with dimensions to a target tensor